newPRWelcomeComment: >
  Thanks for taking the time to contribute to hawkBit! We really appreciate this.
  Make yourself comfortable while I'm looking for a committer to help you with your contribution.

  Please make sure you red the [contribution guide](https://github.com/eclipse/hawkbit/blob/master/CONTRIBUTING.md) and signed the Eclipse Contributor Agreement (ECA).
