#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

baseurl = "https://eclipse.dev/hawkbit/"
languageCode = "en-us"
title = "Eclipse hawkBit"
theme = "hugo-material-docs"
metadataformat = "toml"
canonifyurls = false

[markup]
	[markup.goldmark]
		[markup.goldmark.extensions]
			typographer = true
        [markup.goldmark.renderer]
            unsafe = true

[markup.highlight]
	codeFences = false

[params]
	# General information
	author = "The Eclipse hawkBit Project"
	description = "IoT. Update. Device."
	copyright = "The Eclipse hawkBit Project"
	logo = "images/hawkbit_icon.png"
	favicon = "images/favicon.ico"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/eclipse/hawkbit"

	permalink = "#"

	# Custom assets
	custom_css = ["css/hawkbit.css","//www.eclipse.org/eclipse.org-common/themes/solstice/public/stylesheets/vendor/cookieconsent/cookieconsent.min.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

[params.palette]
	primary = "deep-purple"
	accent  = "light-green"

[params.font]
	text = "Ubuntu"
	code = "Ubuntu Mono"

[social]
	github  = "eclipse/hawkbit"
	gitter  = "eclipse/hawkbit"
	docker  = "hawkbit"

[[menu.main]]
	name   = "What is hawkBit"
	url    = "/whatishawkbit/"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "/gettingstarted/"
	weight = 20

[[menu.main]]
	name   = "Guides"
	url    = "/guides/"
	weight = 30

[[menu.main]]
	name   = "Features"
	url    = "/features/"
	weight = 40

[[menu.main]]
	name   = "Concepts"
	url    = "/concepts/"
	weight = 50

[[menu.main]]
	name   = "Architecture"
	url    = "/architecture/"
	weight = 60

[[menu.main]]
	name   = "Management UI"
	url    = "/ui/"
	weight = 70

[[menu.main]]
	name   = "APIs"
	url    = "/apis/"
	weight = 80

[[menu.main]]
	name   = "Release notes"
	url    = "/release-notes/"
	weight = 90

[[menu.main]]
	name   = "Blog"
	url    = "/blog/"
	weight = 100

[[menu.main]]
	name   = "Community"
	url    = "/community/"
	weight = 110
