#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

version: 2
jobs:
  build:

    working_directory: ~/hawkBit

    docker:
    - image: cimg/openjdk:17.0.8
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_ACCESSTOKEN
      environment:
        _JAVA_OPTIONS: "-Xms512m -Xmx1024m"

    - image: rabbitmq:3-management
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_ACCESSTOKEN
      environment:
        RABBITMQ_DEFAULT_VHOST: "/"

    steps:

    - checkout

    - restore_cache:
        key: circleci-hawkbit-{{ checksum "pom.xml" }}

    - run:
       name: Install dependencies without testing
       command: mvn install --batch-mode -DskipTests

    - run:
        name: Run tests incl. license check
        command: './.circleci/run-qa.sh'

    - run:
        name: Record test results
        command: mkdir -p testresults/jUnit && find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} testresults/jUnit/ \;

    - store_test_results:
        path: testresults

    - store_artifacts:
        path: pom.xml
        destination: pom.xml

    - save_cache:
        paths:
        - ~/.m2
        key: circleci-hawkbit-{{ checksum "pom.xml" }}
