name: Mark & close stale issues

on:
  # enable running the workflow manually
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  issues: write
  # only needed if marking PRs as stale
#  pull-requests: write

jobs:
  stale:
    # only on original eclipse-hawkbit/hawkbit repo
    if: github.repository == 'eclipse-hawkbit/hawkbit'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.PAT_SECRET }}
          # disables automatic marking of issues as stale
          days-before-stale: -1
          days-before-close: 15
          stale-issue-label: 'awaiting'
          close-issue-message: |-
            There has been no response from the original author so I closed this issue.
            Please reach out if you have or find the answers we need so that we can investigate further.
          only-labels: 'awaiting'