name: Verify (Hibernate)

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.3rd-party/**'
      - 'docs/**'
      - 'site/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.3rd-party/**'
      - 'docs/**'
      - 'site/**'
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-hibernate:
    uses: ./.github/workflows/reusable_workflow_verify.yaml
    with:
      repository: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
      maven_properties: '-Djpa.vendor=hibernate -Dlogging.level.org.hibernate.collection.spi.AbstractPersistentCollection=ERROR'